name: decode_dev

channels:
#  - turagalab/label/dev
#  - turagalab/label/rc
  - turagalab
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  # for building
  - bump2version

  # docs
  - recommonmark  # markdown for sphinx
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx-markdown-tables
  - pydata-sphinx-theme

  # actual package
  - python>=3.8,<4
  - pytorch=1.7.1
  - cpuonly  # or cudatoolkit
  - click
  - deprecated
  - gitpython>=3.1
  - h5py
  - line_profiler
  - matplotlib
  - pandas
  - pytest
  - pyyaml
  - requests
  - scipy
  - seaborn=0.10
  - scikit-image
  - scikit-learn
  - spline=0.10.0
  - tensorboard
  - tifffile>=2020.2
  - tqdm
