name: decode_dev_cuda

channels:
  - turagalab/label/dev
  - turagalab
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # for building (decode and splinepsf)
  - bump2version
  - cmake=3.15
  - ninja
  - pybind11>=2.4

  # docs
  - recommonmark  # markdown for sphinx
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx_rtd_theme

  # actual package
  - python=3.9
  - pytorch=1.7.1
  - cudatoolkit
  - torchvision
  - click
  - deprecated
  - h5py
  - line_profiler
  - matplotlib
  - pandas
  - pytest
  - pyyaml
  - requests
  - scipy
  - seaborn=0.10
  - scikit-image
  - scikit-learn
  - spline>=0.10.alpha
  - tensorboard
  - tifffile>=2021.1
  - tqdm

  # add kernel to jupyter
  - ipykernel
