# <<<  Compiler Stuff  >>>
c_compiler:
    - clang                            # [osx]
    - gcc                              # [linux]
    - vs2017                           # [win]
cxx_compiler:
    - clangxx                          # [osx]
    - gxx                              # [linux]
    - vs2017                           # [win]
target_platform:
    - osx-64                           # [osx]
    - linux-64                         # [linux]
    - win-64                           # [win]
# CONDA_BUILD_SYSROOT:
#     - /Users/travis/MacOSX10.9.sdk     # [osx]
c_compiler_version:
    - 7.3.0                            # [linux]
    - 9                                # [osx]
cxx_compiler_version:
    - 7.3.0                            # [linux]
    - 9                                # [osx]

python:
    - 3.6
    - 3.7
    - 3.8

numpy:
    - 1.18